apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: "target-type=ip"
spec:
  selector:
    app: nodejs-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
