apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-container
        image: 891377191404.dkr.ecr.us-east-1.amazonaws.com/nodejs-eks-app:latest
        ports:
        - containerPort: 3000
